### ISSUE TITLE
Problems after migration to version 2.0+

### ISSUE THREAD

**Issue by egorikftp** [pandulapeter/beagle#56] opened 2020-09-28 14:18 UTC
Hello, thanks again for the great library. 

We have faced several issues after migration to beagle drawer-layout.
I see that now the base implementation uses a fragment under the hood. It introduced a few problems:

1. We use Accessibility an application and now `OverlayFragment` request focus all the time due to he is a root 🙂 
2. Due to we have a legacy code we sometimes replace fragment in `android.R.id.content` and in this case we lose Beagle on this screen)

Thanks a lot.

**Comment by pandulapeter** [comment] 2020-09-28 14:56
Hi,

Sorry to hear about these problems. Both of your issues make perfect sense and come down to some core design decisions on my side. Unfortunately, I don't yet have a good solution, but let me give you some explanations, maybe together we will figure something out:

1. `OverlayFragment` is indeed added on top of every Activity: in case of the drawer it is responsible for Beagle's UI (the old versions' hacky way of removing the root View of every Activity and "injecting" a DrawerLayout instead was glitchy, hacky and probably introduced more problems - this solution feels a lot cleaner). Furthermore it also handles persmissions / Activity results (for the screenshot / screen capture features) and hosts the `OverlayView` which provides a way for drawing over the UI (for example the `KeylineOverlaySwitchModule` relies on it). Obviously `OverlayFragment` should not affect the functionality of the underlying app in any way apart from these. I didn't work with accessibility that much, do you maybe know a simple fix for not stealing the focus? How can we forward these events without knowing what's below?

2. Three ideas:
a) If your legacy code happens to rely on the FragNav library, [this workaround](https://github.com/pandulapeter/beagle/issues/35) might help.
b) I could add an optional lambda to the Beagle configuration's Behavior object: it would receive an Activity type parameter and would expect an ID resource in response that can be used as OverlayFragment's container. Unfortunately this also would need some refactoring of your legacy codebase to add empty FrameLayouts over the Activities. Anyway, would this help?
c) What do you think, in the `addOverlayFragment()` function of [this class](https://github.com/pandulapeter/beagle/blob/master/core/src/main/java/com/pandulapeter/beagle/core/manager/UiManagerContract.kt), if we used `add()` instead of `replace()` - could that fix your issue? Probably not, since in your case your own implementation seems to be calling `replace()` after Beagle, so the debug menu wouldn't be added to the top (and we could also introduce some unwanted stack handling issues).

All in all: I'll let you know if I have any other ideas but right now the best that I can say is that in release builds your app will work as expected (the `noop` library surely won't break focus handling). Do you maybe have any ideas that we could try? If you have the time and feel like experimenting, maybe consider cloning this repository ([here is a guide](https://github.com/pandulapeter/beagle/blob/master/metadata/DOCUMENTATION.md) that will help with the module structure).

Thanks for the bug report!

**Comment by pandulapeter** [comment] 2020-09-29 13:29
@egorikftp Could you maybe give me some repro steps for the first issue? If I have an empty Activity with Beagle enabled vs Beagle disabled, what should I add to reproduce this focusability problem? I've only tested keyboard handling which seems to work the same in either case.

**Comment by egorikftp** [comment] 2020-09-29 14:18
@pandulapeter Thanks for the quick response)

According to the accessibility issue. I think this case can't be fixed by your side due to the strange behaviour of fragments with accessibility.

https://medium.com/@guygriv/accessibility-and-fragment-transactions-1aef5596f9d4

We use this hack to focus only first fragment in the stack. In this case, the best option for us is to make our own logic for shipping `OverlayFragment` from the hierarchy.

If we speak about proposed workarounds:
a. Not our solution, we don't use any navigation libraries)
b. Also won't help, because we use `android.R.id.content` as a container to show fullscreen fragment.
c. Looks like work solution but has some side effects. I see that right now we also use `replace` for our fragments, but I tried to use `add` instead and for first look everything works as expected. The problem reproduced with enabled accessibility.

The activity starts and OverlayFragment added, then I add my own fragment and Beagle doesn't work because he second in the stack 🙂 

I think the best option for us is to refactor the existing approach, remove any usages of `android.R.id.content` and don't request focus on OverlayFragment.

**Comment by pandulapeter** [comment] 2020-09-29 14:56
Thanks for the clarification. I'm sorry I couldn't help more, but to summarize:

1) The accessibility / focusability problem comes down to implementation details on your side, if those are non-standard, as you mentioned, you have to find ways to work around them. Based on the article, maybe you can disregard OverlayFragment when searching for the Fragment on top: if you decide to do so, consider hardcoding its package name (`com.pandulapeter.beagle.core.OverlayFragment`)  or tag (`beagleOverlayFragment`) , since the class itself won't be present in release builds (due to the `noop` dependency).

2) Beagle using `android.R.id.content` as a Fragment container is a hack on my side and I couldn't find a better solution to inject the debug menu on top of any Activity. As a result, I'll try to highlight this limitation more in the readme file but as it won't be fixed, I'll close this issue. I hope you don't have to refactor too many things, sorry for the inconvenience :(

Let me know if you find anything else!

**Closed by pandulapeter** 2020-09-29 14:56 UTC
Labels: bug

**Comment by pandulapeter** [comment] 2020-09-29 16:08
One more update: I've played around a bit with the back stack listener in [this commit](https://github.com/pandulapeter/beagle/commit/cc884df9b3b2c20f9b67c889db15f4df37488c31) and there is a slight chance that these changes will fix your second issue. Theoretically now the OverlayFragment should be re-added to the top of the stack every time the stack changes.

If you haven't given up on the library yet, could you give it a try? These changes are part of the [new v2.0.3 release](https://github.com/pandulapeter/beagle/releases/tag/2.0.3).
