### ISSUE TITLE
Theme issue

### ISSUE THREAD

**Issue by Shusshu** [pandulapeter/beagle#3] opened 2019-10-15 11:56 UTC
In order to make the app startup nicer I have set a StartupTheme in my manifest for my LauncherActivity and I set my actual theme in onCreate
See:
https://developer.android.com/topic/performance/vitals/launch-time#solutions-3

Beagle is not using the new theme set in my activity before `setContentView` but the one from the manifest

**Comment by pandulapeter** [comment] 2019-10-15 12:09
That's a pretty good pattern and I'm doing the same thing on a project where Beagle is added. The circumstances are a bit different and I didn't encounter this issue; I'm investigating this right now and will update the example project if I find something.

Anyway, there is a quick fix. You should specify the theme for Beagle when you initialize it:

`Beagle.imprint(
                application = this,
                appearance = Appearance(themeResourceId = R.style.YourTheme)
            )`

**Comment by pandulapeter** [comment] 2019-10-15 12:11
Feel free to close the issue if the solution I mentioned fixes it :)

**Comment by Shusshu** [comment] 2019-10-15 13:11
I already did that but it uses the theme for the drawer part but the main screen background is still using the StartupTheme windowBackground

**Comment by pandulapeter** [comment] 2019-10-15 13:29
I've just updated the example app to include a splash screen (check it out, it's part of this repo) and cannot reproduce your issue. Here's what I did:

- Create a Splash theme (with a different background) and set it for the Application in the Manifest.
- Set each Activity's theme in the onCreate() method, before calling the super implementation.

You can see all these changes [here](https://github.com/pandulapeter/beagle/commit/7e3c2cb782851645c1cb567434b901f8f646b2ff).

As far as I know, this is the cleanest implementation for splash screens (without introduing artificial startup delays) and can't see any problem with the library's behavior. Please let me know how your implementation differs. If what I'm suggesting is suitable for your app, it might fix your other issue as well.

**Comment by pandulapeter** [comment] 2019-10-15 13:31
Please note that if you remove Beagle's custom theme from my code, it will still take the Activity's theme not the Splash theme, as expected. I really don't see how changing the root of the layout messes up your Activity theme, so it has to be some other issue... Let me know what you find!

**Closed** 2019-10-30 07:43 UTC
