### ISSUE TITLE
Drawer does not work with FragNav

### ISSUE THREAD

**Issue by jakoss** [pandulapeter/beagle#35] opened 2020-08-17 11:01 UTC
I'm using FragNav for fragments navigation (https://github.com/ncapdevi/FragNav) and when i set up MainActivity like this:

```kotlin
@AndroidEntryPoint
class MainActivity : AppCompatActivity(), FragNavController.TransactionListener {
    private val binding by viewBinding(ActivityMainBinding::inflate)

    val fragNavController = FragNavController(supportFragmentManager, R.id.fragmentContainer)

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.AppTheme)
        super.onCreate(savedInstanceState)
        setContentView(binding.root)

        fragNavController.apply {
            transactionListener = this@MainActivity
            rootFragments = listOf(HomeFragment())
            fragNavLogger = object : FragNavLogger {
                override fun error(message: String, throwable: Throwable) {
                    Timber.e(throwable, message)
                }
            }

            defaultTransactionOptions = FragNavTransactionOptions.newBuilder().customAnimations(
                R.anim.slide_left_from_right,
                R.anim.slide_left_from_middle,
                R.anim.slide_right_from_left,
                R.anim.slide_right_from_middle
            ).build()
            initialize(savedInstanceState = savedInstanceState)
        }
    }
}
```

the `Beagle.show()` returns false. When i inspect layout - no overlay is being added. If i disable FragNav like this:

```kotlin
@AndroidEntryPoint
class MainActivity : AppCompatActivity() {
    private val binding by viewBinding(ActivityMainBinding::inflate)

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.AppTheme)
        super.onCreate(savedInstanceState)
        setContentView(binding.root)

        supportFragmentManager.commit {
            replace(R.id.fragmentContainer, HomeFragment())
        }
    }
}
```

It works perfectly. FragNav is pretty important to me. Is there a way to bypass this issue?

**Comment by pandulapeter** [comment] 2020-08-17 11:42
Hi,

Thanks for the bug report, this sounds interesting! I've never used FragNav so I'm investigating this right now (I've managed to reproduce the issue). Should be something simple, as apparently [this addOverlayFragment() function](https://github.com/pandulapeter/beagle/blob/master/core/src/main/java/com/pandulapeter/beagle/core/manager/UiManagerContract.kt) fails to do its job, my first guess was that FragNav is replacing the Fragment in the **android.R.id.content** FrameLayout with something else but looks like that's not the case. Anyway,  I'll let you know when I find something.

**Comment by pandulapeter** [comment] 2020-08-17 12:13
I think I found it.

During its [initialize() function, in line 201](https://github.com/ncapdevi/FragNav/blob/master/frag-nav/src/main/java/com/ncapdevi/fragnav/FragNavController.kt#L201) FragNav removes all Fragments from the FragmentManager (which at that moment already contains the OverlayFragment needed for Beagle). Now, maybe I could introduce a small delay to circumvent this but [this comment is pretty clear](https://github.com/ncapdevi/FragNav/blob/master/frag-nav/src/main/java/com/ncapdevi/fragnav/FragNavController.kt#L633), and we might introduce further issues down the road. Exposing the OverlayFragment for you to manually add is cumbersome + can introduce issues with the release build.

I think I have a solution but I'd kindly ask you to give it a try with your setup. Could you let Beagle use the Activity's supportFragmentManager and initialize FragNav within a Fragment, using that Fragment's childFragmentManager? From what I saw, that could work and would be a relatively quick fix (besides introducing a Fragment into the hierarchy...). Will this fix your issue? If it does, is it too much overhead when using FragNav?

I'll think about it a bit more but for now I don't see a fix that won't affect other users negatively (people using manual Fragment management / Jetpack Navigation).

**Comment by jakoss** [comment] 2020-08-17 12:20
Ok, so i changed my activity to this:
```kotlin
class MainActivity : AppCompatActivity() {
    private val binding by viewBinding(ActivityMainBinding::inflate)

    override fun onCreate(savedInstanceState: Bundle?) {
        setTheme(R.style.AppTheme)
        super.onCreate(savedInstanceState)
        setContentView(binding.root)

        supportFragmentManager.commit {
            replace(R.id.activityFragmentContainer, MainNavigationFragment())
        }
    }
}
```

and MainNavigationFragment looks like this:
```kotlin
class MainNavigationFragment : Fragment(R.layout.fragment_main_navigation) {
    val fragNavController by lazy {
        FragNavController(
            childFragmentManager,
            R.id.fragmentContainer
        )
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)

        fragNavController.apply {
            rootFragments = listOf(HomeFragment())
            fragNavLogger = object : FragNavLogger {
                override fun error(message: String, throwable: Throwable) {
                    Timber.e(throwable, message)
                }
            }

            defaultTransactionOptions = FragNavTransactionOptions.newBuilder().customAnimations(
                R.anim.slide_left_from_right,
                R.anim.slide_left_from_middle,
                R.anim.slide_right_from_left,
                R.anim.slide_right_from_middle
            ).build()
            initialize(savedInstanceState = savedInstanceState)
        }

        requireActivity().onBackPressedDispatcher.addCallback(viewLifecycleOwner, backCallback)
    }
}
```
And it works fine so far. I don't think that one more fragment in hierarchy will drastically impact the performance, so this is ok for me 👍🏻

**Comment by jakoss** [comment] 2020-08-17 12:28
Also, is it necessary to create Overlay while using dialog or bottom sheet menu?

**Comment by pandulapeter** [comment] 2020-08-17 12:34
Awesome 👍 And thanks for posting the code as well.

Yeah, the OverlayFragment does a couple of things: while you're right that its View hierarchy is only used for the Drawer, it also handles some Activity Results (screenshot, screen recording) and the keyline overlay module which must work for all types, so it must be added.

I'll close this one for now, I think this is a reasonable workaround and a more elegant solution would be the ability to whitelist some Fragment tags in FragNav which don't depend on us. Thanks for bringing it up, let me know if you find anything else!

**Closed by pandulapeter** 2020-08-17 12:34 UTC
